[build]
builder = "nixpacks"

[deploy]
startCommand = "npm install && npm run railway:deploy"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
PORT = "5000"