[build]
builder = "nixpacks"

[deploy]
startCommand = "node start-script.cjs"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
PORT = "5000"